# Generated by Django 5.1 on 2024-09-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('age', models.IntegerField(max_length=2)),
                ('name', models.CharField(max_length=20)),
                ('pho', models.IntegerField(max_length=10)),
            ],
        ),
    ]
