# Generated by Django 5.1 on 2024-09-25 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiModelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=20)),
                ('studentId', models.IntegerField()),
                ('studentsection', models.CharField(max_length=30)),
                ('studentmark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MultiModelApp.student')),
                ('schoolname', models.CharField(max_length=100)),
            ],
            bases=('MultiModelApp.student',),
        ),
    ]
