# Generated by Django 5.1 on 2024-09-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultiModelApp', '0002_student_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['studentname']},
        ),
    ]
